### Get all products
GET http://localhost:3001/products

### Add a product
POST http://localhost:3001/products
Content-Type: application/json

{
  "name": "Keyboard",
  "price": 49.99,
  "quantity": 1
}

### Update a product
PUT http://localhost:3001/products/1
Content-Type: application/json

{
  "name": "PenEdit",
  "price": 100.00,
  "quantity": 5
}

### Delete Product
DELETE http://localhost:3001/products/1